#!/usr/bin/env python3
"""
index_entries.py — regenerate INDEX.md from entries/*.md.

Pulls each entry's first heading and first paragraph as a one-line
summary. Run this after adding a new entry:

    python3 index_entries.py
"""

import pathlib
import re

ROOT = pathlib.Path(__file__).parent
ENTRIES_DIR = ROOT / "entries"
INDEX_PATH = ROOT / "INDEX.md"


def summarize(path: pathlib.Path) -> tuple[str, str]:
    text = path.read_text()
    heading_match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    heading = heading_match.group(1).strip() if heading_match else path.stem

    body = text[heading_match.end():] if heading_match else text
    paragraphs = [p.strip() for p in re.split(r"\n\s*\n", body) if p.strip()]
    first_para = paragraphs[0] if paragraphs else ""
    first_para = re.sub(r"\s+", " ", first_para)
    if len(first_para) > 160:
        first_para = first_para[:157].rstrip() + "..."

    return heading, first_para


def main() -> None:
    entries = sorted(ENTRIES_DIR.glob("*.md"))
    if not entries:
        print("No entries found.")
        return

    lines = [
        "# Index",
        "",
        "Auto-generated by `index_entries.py`. Do not edit by hand — run the",
        "script again after adding a new entry.",
        "",
    ]

    for path in entries:
        heading, summary = summarize(path)
        rel = path.relative_to(ROOT)
        lines.append(f"### [{heading}]({rel})")
        if summary:
            lines.append("")
            lines.append(summary)
        lines.append("")

    INDEX_PATH.write_text("\n".join(lines).rstrip() + "\n")
    print(f"wrote {INDEX_PATH} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
